modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL=""
displayURL=""
credits="TeychMan"

[[mods]]
modId="copycoords"
version="1.0.0"
displayName="Copy Coords Mod"
description='''
Copy Coords Mod - удобный мод для Minecraft, который позволяет копировать координаты игрока в буфер обмена одним нажатием назначенной клавиши.
Поддерживается настройка формата координат через шаблоны, включая {x}, {y}, {z} и {world}.
'''
authors="TeychMan"
